default:
  image: ubuntu:18.04
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp

build:
  script:
    # Sync to FTP
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST -p $PORT; mirror -Rnev ./ $PATH --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  only:
    - master